version: '3.4'

services:
  webserver:
    image: nginx:latest
    restart: always
    ports: 
      - "8080:80"
    volumes: 
      - ./websites:/usr/share/nginx/html
    depends_on:
      - db
    links:
      - db
  

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=34jgefogh
    restart: always
    volumes: 
      - "/var/lib/mysql"

volumes:
  db_vol:
    

